"use strict";
const $=id=>document.getElementById(id), tokenKey="descles-edge-admin";
let token="", info=null, me=null, panels=[], active="overview";
const sections={
 overview:["Overview","EDGE HEALTH","Your agents, providers and recent activity in one place.","overview"],
 providers:["Providers","UPSTREAM CREDENTIALS","Add provider keys on this edge. Keys never appear in list responses.","providers"],
 teams:["Teams","LOCAL GROUPS","Group agents for policy rules on this edge.","agents"],
 agents:["Agents & keys","ACCESS","Issue, rotate and revoke virtual keys. A new key is shown once.","agents"],
 users:["Users & access","CONSOLE IDENTITIES","See who can use this console and what each role can do.","agents"],
 models:["Model traces","OBSERVABILITY","Model calls and token usage recorded locally.","runs"],
 tools:["Tool traces","OBSERVABILITY","Executed or checked tools and policy decisions.","activity"],
 audit:["Audit","LOCAL RECORDS","Activity, approvals and local configuration changes.","audit"],
 approvals:["Approvals","HUMAN REVIEW","Review calls awaiting an administrator decision.","approvals"],
 policy:["Policy","ENFORCEMENT","Inspect and test the policy this edge enforces.","policies"],
 integrations:["Data integration","PREMIUM · CONTEXT","See source sync, claim extraction and connector health.","providers"],
 context:["Organization context","PREMIUM · CONTEXT","Explore permission-aware entities, citations and conflicting claims.","agents"],
 mining:["Trace mining","PREMIUM · LEARNING","Find repeated tool paths and prepare a reviewed workflow.","activity"],
 workflows:["Deterministic workflows","PREMIUM · LEARNING","Review a mined draft and run an approved plan through this edge.","policies"],
 plans:["Upgrade plan","TEAM & PREMIUM","More governance and context, hosted in your network.","coverage"]
};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n}
function add(parent,...children){for(const c of children)parent.append(c);return parent}
function clear(node){node.replaceChildren();return node}
function card(title){const c=el("section","card"),h=el("h2",null,title);c.append(h);return c}
function note(text){return el("div","note",text)}
function empty(text){return el("div","edge-empty",text)}
function field(label,type="text",value="",name=""){const l=el("label",null,label),i=el("input");i.type=type;i.value=value;i.name=name||label.toLowerCase().replace(/[^a-z0-9]+/g,"_");l.append(i);return [l,i]}
function button(label,fn,secondary=false){const b=el("button",secondary?"secondary":"",label);b.type="button";b.onclick=fn;return b}
function table(headers,rows){const wrap=el("div","table-wrap edge-table"),t=el("table"),head=el("tr");for(const h of headers)head.append(el("th",null,h));t.append(head);for(const values of rows){const tr=el("tr");for(const v of values){const td=el("td");if(v instanceof Node)td.append(v);else td.textContent=v==null?"":String(v);tr.append(td)}t.append(tr)}wrap.append(t);return wrap}
function fmt(t){return t?new Date(t).toLocaleString():"—"}
function toast(msg){const n=$("notice");n.textContent=msg;n.hidden=false;setTimeout(()=>{n.hidden=true},5500)}
function detail(title,...contents){$("detail-title").textContent=title;const body=add(clear($("detail-body")),...contents);if(me?.role==="viewer"||me?.role==="team_viewer")for(const b of body.querySelectorAll("button"))if(/^(Review draft|Run workflow|Record review|Run approved workflow)$/.test(b.textContent.trim()))b.disabled=true;if(!$("detail").open)$("detail").showModal()}
async function api(path,options={}){const headers={Authorization:"Bearer "+token,...options.headers};if(options.body&&typeof options.body!=="string"){headers["Content-Type"]="application/json";options.body=JSON.stringify(options.body)}const response=await fetch(path,{...options,headers,cache:"no-store"});if(response.status===401){disconnect();throw Error("Admin token rejected. Connect again.")}if(!response.ok){const raw=await response.text();let message=raw.trim();try{message=JSON.parse(raw).error||message}catch{}const err=Error(message||`Request failed (${response.status})`);err.status=response.status;throw err}return response.json()}
function disconnect(){token="";sessionStorage.removeItem(tokenKey);info=null;me=null;$("workspace").hidden=true;$("login").hidden=false;$("signout").hidden=true;$("identity").hidden=true;$("connection").textContent="Disconnected"}
async function connect(value){token=value.trim();info=await api("/admin/info");me=await api("/admin/me");sessionStorage.setItem(tokenKey,token);$("login").hidden=true;$("workspace").hidden=false;$("signout").hidden=false;$("identity").hidden=false;$("identity").textContent=`${me.name} · ${me.role}${me.team_ids?.length?" · "+me.team_ids.join(", "):""}`;$("connection").textContent=(info.edge_id||"Edge")+" · "+info.mode;panels=(await api("/admin/panels")).panels||[];if(!me.role.startsWith("team_"))for(const [id,path] of [["context","/admin/context/sync"],["learning","/admin/learning/workflows"]]){if(panels.some(p=>p.id===id)){try{await api(path)}catch(e){if(e.status===402)panels=panels.filter(p=>p.id!==id)}}}nav();await show((location.hash||"#overview").slice(1))}
const hasPanel=id=>panels.some(p=>p.id===id);
function nav(){const managed=info.mode==="managed",scoped=me?.role?.startsWith("team_"),groups=[
 [scoped?"YOUR TEAMS":"YOUR EDGE",scoped?["overview","teams","agents","models","tools","audit","approvals"]:managed?["overview","users","models","tools","audit","approvals","policy"]:["overview","providers","teams","agents","users","models","tools","audit","approvals","policy"]],
 ["EXPAND YOUR EDGE",scoped?["plans"]:["integrations","context","mining","workflows","plans"]]
 ];const n=clear($("navigation"));for(const [title,ids] of groups){const group=el("div","nav-group"),heading=el("div","nav-heading",title);group.append(heading);for(const id of ids){const a=el("a",id===active?"active":"");a.href="#"+id;a.dataset.icon=sections[id][3];a.append(el("span","nav-text",sections[id][0]));if(["integrations","context","mining","workflows"].includes(id)&&!hasPanel(id==="integrations"?"context":id==="workflows"?"learning":id==="mining"?"learning":id))a.append(el("span","nav-lock","PLUS"));a.onclick=e=>{e.preventDefault();show(id)};group.append(a)}n.append(group)}}
function applyAccess(v){if(!["viewer","team_viewer"].includes(me?.role))return;v.prepend(note("Viewer access is read-only. Ask the owner for admin access to change settings or decide approvals."));for(const f of v.querySelectorAll("form")){const label=f.querySelector("button")?.textContent?.trim();if(!["Search","Check"].includes(label))for(const control of f.querySelectorAll("input,select,textarea,button"))control.disabled=true}for(const b of v.querySelectorAll("button"))if(/^(Remove|Rotate|Revoke|Sync now|Approve|Deny|Review draft|Run workflow|Mine selected traces|Record finding)$/.test(b.textContent.trim()))b.disabled=true}
async function show(id){if(!sections[id]||(me?.role?.startsWith("team_")&&!new Set(["overview","teams","agents","models","tools","audit","approvals","plans"]).has(id)))id="overview";active=id;location.hash=id;nav();const s=sections[id];$("breadcrumb").textContent=s[0];$("eyebrow").textContent=s[1];$("page-title").textContent=s[0];$("page-description").textContent=s[2];$("page-icon").dataset.icon=s[3];const v=clear($("view"));v.append(el("div","loading","Loading…"));try{await views[id](v);applyAccess(v)}catch(e){clear(v).append(el("div","error-panel",e.message))}}
const refresh=()=>show(active);
const views={
 async overview(v){const scoped=me.role.startsWith("team_");const [a,p,g,t,u]=await Promise.all([api("/admin/activity?limit=100"),info.mode==="standalone"&&!scoped?api("/admin/providers"):Promise.resolve({providers:[]}),info.mode==="standalone"?api("/admin/agents"):Promise.resolve({agents:[]}),api("/admin/approvals?state=pending"),api("/admin/usage?days=14")]);const records=a.records||[],models=records.filter(r=>r.kind==="model"),tools=records.filter(r=>r.kind==="tool"),days=u.days||[],input=days.reduce((n,d)=>n+d.input_tokens,0),output=days.reduce((n,d)=>n+d.output_tokens,0),cost=days.reduce((n,d)=>n+d.cost_usd,0);const grid=el("div","edge-grid");for(const [title,value,hint] of [["Input tokens",input.toLocaleString(),"Last 14 days"],["Output tokens",output.toLocaleString(),"Last 14 days"],["Agents",g.agents.length,"Virtual identities"],["Pending",t.approvals.length,"Need a decision"]]){const c=card(title);add(c,el("strong","edge-number",value),el("small","muted",hint));grid.append(c)}clear(v).append(grid);const usage=card("Token usage · last 14 days"),chart=el("div","usage-chart"),max=Math.max(1,...days.map(d=>d.input_tokens+d.output_tokens));chart.setAttribute("role","img");chart.setAttribute("aria-label",days.map(d=>`${d.day}: ${d.input_tokens} input, ${d.output_tokens} output tokens`).join("; "));for(const d of days){const col=el("div","usage-day");col.title=`${d.day}: ${d.input_tokens.toLocaleString()} input, ${d.output_tokens.toLocaleString()} output tokens`;const out=el("span","usage-bar output"),inp=el("span","usage-bar input");out.style.height=`${Math.max(2,d.output_tokens/max*170)}px`;inp.style.height=`${Math.max(2,d.input_tokens/max*170)}px`;col.append(out,inp);chart.append(col)}usage.append(chart,el("div","usage-labels"));usage.lastChild.append(el("span",null,days[0]?.day||""),el("span",null,days.at(-1)?.day||""));const legend=el("div","usage-legend");legend.append(el("span",null,"Input tokens"),el("span","output","Output tokens"));usage.append(legend,el("p","muted",`${days.reduce((n,d)=>n+d.calls,0)} model calls · $${cost.toFixed(4)} estimated cost${u.limited?" · recent-record cap reached; totals may be incomplete":""}`));v.append(usage,note(scoped?`Showing only ${me.team_ids.join(", ")} team data on this edge.`:`Edge ${info.edge_id} is running in ${info.mode} mode. ${p.providers.length} providers configured. Credentials and traces remain on this edge.`));const c=card("Recent activity");c.append(activityTable(records.slice(0,12)));v.append(c);if(info.mode==="managed")v.append(note("Team and provider administration lives in the customer-hosted workspace at /. This edge retains local traces and approvals."))},
 async users(v){const d=await api("/admin/operators");clear(v);const intro=card("Your console identity");intro.append(el("p",null,`${me.name} (${me.id}) · ${me.role}${me.shared?" · shared recovery credential":""}`));v.append(intro);const c=card("Console users");c.append(table(["User","ID","Role","Scope","Access"],(d.users||[]).map(u=>[u.name,u.id,u.role,u.team_ids?.join(", ")||"Entire edge",u.shared?"Shared owner recovery token":me.role==="owner"?button("Revoke",async()=>{if(!confirm(`Revoke ${u.name}'s console access?`))return;try{await api("/admin/operators/"+encodeURIComponent(u.id),{method:"DELETE"});toast("Access revoked");refresh()}catch(err){toast(err.message)}},true):"Named token"])));v.append(c);const matrix=card("What roles can do");matrix.append(table(["Role","Access"],[["Owner","All console actions and user management. Keep this bootstrap token for recovery."],["Admin","View and change edge configuration, issue agent keys, review approvals and run licensed features."],["Viewer","Read console data and check policy. Cannot change settings or approve actions."],["Team admin","Manage agent keys and approvals only for assigned teams; view their activity and audit."],["Team viewer","Read activity, approvals and team audit only for assigned teams."]]));v.append(matrix);if(me.role==="owner"){const form=card("Add a console user"),f=el("form","edge-form"),[id,ii]=field("User ID","text","","id"),[name,ni]=field("Display name","text","","name"),roleLabel=el("label",null,"Role"),role=el("select"),teamsLabel=el("label",null,"Team scope"),teams=el("select");for(const value of ["viewer","admin","team_viewer","team_admin"]){const option=el("option",null,value);option.value=value;role.append(option)}const choices=await api("/admin/teams");for(const team of choices.teams||[]){const option=el("option",null,team.name);option.value=team.id;teams.append(option)}teamsLabel.append(teams);roleLabel.append(role);role.onchange=()=>{teamsLabel.hidden=!role.value.startsWith("team_")};teamsLabel.hidden=true;ii.required=ni.required=true;ii.placeholder="alice";ni.placeholder="Alice Smith";f.append(id,name,roleLabel,teamsLabel,el("button",null,"Create access token"));f.onsubmit=async e=>{e.preventDefault();try{const result=await api("/admin/operators",{method:"POST",body:{id:ii.value,name:ni.value,role:role.value,team_ids:role.value.startsWith("team_")?[teams.value]:[]}});detail("Console token for "+ni.value,el("p",null,"Copy this token now and give it only to this person. It will not be shown again."),el("pre","edge-key",result.token));refresh()}catch(err){toast(err.message)}};form.append(f);v.append(form)}v.append(note("Agent keys are separate from console access. Bind each agent key to a user and team in Agents & keys so traces and policy decisions identify the acting user."))},
 async providers(v){const d=await api("/admin/providers");const c=card("Configured providers");const rows=d.providers.map(p=>[p.name,p.base_url,(p.models||[]).join(", ")||"Default",p.has_key?"Stored on edge":"Missing",p.source,p.source==="console"?button("Remove",async()=>{if(!confirm(`Remove provider ${p.name}?`))return;await api("/admin/providers/"+encodeURIComponent(p.name),{method:"DELETE"});toast("Provider removed");refresh()},true):"Save the same name below to replace"]);c.append(rows.length?table(["Provider","Endpoint","Models","Key","Source","Action"],rows):empty("No provider configured yet."));const form=card("Add or replace provider");const f=el("form","edge-form");const [name,ni]=field("Provider name","text","","name"),[base,bi]=field("Base URL","url","","base_url"),[key,ki]=field("API key","password","","api_key"),[models,mi]=field("Model patterns, comma separated","text","","models");for(const i of [ni,bi,ki])i.required=true;ni.placeholder="openai";bi.placeholder="https://api.openai.com/v1";mi.placeholder="gpt-*, o4-mini";f.append(name,base,key,models,el("button",null,"Save provider"));f.onsubmit=async e=>{e.preventDefault();try{await api("/admin/providers",{method:"POST",body:{name:ni.value,base_url:bi.value,api_key:ki.value,models:mi.value.split(",").map(s=>s.trim()).filter(Boolean)}});ki.value="";toast("Provider is ready for new model calls");refresh()}catch(err){toast(err.message)}};form.append(f,el("p","edge-help","Console-managed credentials are encrypted with the owner token in the edge data volume. Back up the token separately; changing it requires re-entering these provider keys."));clear(v).append(c,form)},
 async teams(v){const [d,a]=await Promise.all([api("/admin/teams"),api("/admin/agents")]),scoped=me.role.startsWith("team_");const c=card("Teams");c.append(d.teams.length?table(["Team","ID","Agents","Action"],d.teams.map(t=>[t.name,t.id,a.agents.filter(x=>x.group_id===t.id).length,scoped?"Assigned scope":button("Remove",async()=>{if(!confirm(`Remove team ${t.name}?`))return;try{await api("/admin/teams/"+encodeURIComponent(t.id),{method:"DELETE"});refresh()}catch(e){toast(e.message)}},true)])):empty("No teams yet."));clear(v).append(c);if(scoped)return;const form=card("Create team"),f=el("form","edge-form"),[name,ni]=field("Team name","text","","name"),[id,ii]=field("Team ID","text","","id");ni.required=ii.required=true;ii.placeholder="engineering";f.append(name,id,el("button",null,"Create team"));f.onsubmit=async e=>{e.preventDefault();try{await api("/admin/teams",{method:"POST",body:{id:ii.value,name:ni.value}});toast("Team created");refresh()}catch(err){toast(err.message)}};form.append(f);v.append(form)},
 async agents(v){const [d,t]=await Promise.all([api("/admin/agents"),api("/admin/teams")]),scoped=me.role.startsWith("team_");const c=card("Agent keys");const actions=a=>{if(["viewer","team_viewer"].includes(me.role))return "Read only";const box=el("div","edge-actions");box.append(button("Rotate",async()=>{if(!confirm(`Rotate ${a.agent_id}'s key? The old key stops working immediately.`))return;try{const x=await api("/admin/agents/"+encodeURIComponent(a.agent_id)+"/rotate",{method:"POST"});showKey(a.agent_id,x.key);refresh()}catch(e){toast(e.message)}},true),button("Revoke",async()=>{if(!confirm(`Revoke ${a.agent_id} and its key?`))return;try{await api("/admin/agents/"+encodeURIComponent(a.agent_id),{method:"DELETE"});refresh()}catch(e){toast(e.message)}},true));return box};c.append(table(["Agent","User","Team","Action"],d.agents.map(a=>[a.agent_id,a.user_id||"Unassigned",a.group_id||"—",actions(a)])));const form=card("Issue agent key"),f=el("form","edge-form"),[id,ii]=field("Agent ID","text","","id"),[user,ui]=field("Responsible user ID","text","","user_id"),group=el("label",null,scoped?"Team":"Team (optional)"),select=el("select");for(const t0 of scoped?t.teams:[{id:"",name:"No team"},...t.teams]){const o=el("option",null,t0.name);o.value=t0.id;select.append(o)}group.append(select);ii.required=ui.required=true;ii.placeholder="agent-1";f.append(id,user,group,el("button",null,"Issue key"));f.onsubmit=async e=>{e.preventDefault();try{const x=await api("/admin/agents",{method:"POST",body:{id:ii.value,user_id:ui.value,group_id:select.value}});showKey(ii.value,x.key);refresh()}catch(err){toast(err.message)}};form.append(f,el("p","edge-help","The plaintext key is shown once. Only its SHA-256 hash is retained; issuing a key for the same agent requires rotation."));clear(v).append(c,form)},
 async models(v){await traceList(v,"model")},async tools(v){await traceList(v,"tool")},
 async audit(v){const [activity,history,approvals]=await Promise.all([api("/admin/activity?limit=500"),info.mode==="standalone"?api("/admin/audit"):Promise.resolve({events:[],integrity:"not available in managed mode"}),api("/admin/approvals")]);clear(v);v.append(note("Local records are kept on this edge. Configuration history is a convenience log, not a tamper-evident audit ledger."));const events=card("Configuration history");events.append(history.events.length?table(["Time","Operator","Action","Target"],history.events.map(x=>[fmt(x.at),x.actor||"Legacy shared token",x.action,x.target])):empty("No console configuration changes yet."));v.append(events);const ap=card("Approval decisions");ap.append(approvals.approvals.length?table(["Time","Agent","Tool","State","Reviewer"],approvals.approvals.map(x=>[fmt(x.decided_at||x.created_at),x.agent_id,x.tool,x.state,x.decided_by||x.by||"—"])):empty("No approval records yet."));v.append(ap);const calls=card("Model and tool activity");calls.append(activityTable(activity.records));v.append(calls)},
 async approvals(v){const d=await api("/admin/approvals?state=pending");const top=card("Pending approvals");top.append(el("p",null,`Decisions are recorded as ${me.id}.`));clear(v).append(top);if(!d.approvals.length){v.append(empty("Nothing is waiting for a decision."));return}for(const a of d.approvals){const c=card(a.tool),p=el("p","muted",`Agent ${a.agent_id} · requested ${fmt(a.created_at)} · expires ${fmt(a.expires_at)}`),pre=el("pre",null,JSON.stringify(a.args||{},null,2)),[reason,reasonInput]=field("Reason (optional)","text","","reason"),actions=el("div","edge-row"),readonly=["viewer","team_viewer"].includes(me.role);if(!readonly)for(const decision of ["approve","deny"]){actions.append(button(decision==="approve"?"Approve":"Deny",async()=>{try{await api(`/admin/approvals/${encodeURIComponent(a.id)}/${decision}`,{method:"POST",body:{reason:reasonInput.value}});toast("Decision recorded");refresh()}catch(e){toast(e.message)}},decision==="deny"))}v.append(add(c,p,pre,readonly?empty("Viewer access cannot decide approvals."):reason,actions))}},
 async policy(v){const d=await api("/admin/policy"),c=card("Active policy");c.append(el("pre",null,JSON.stringify(d.rules,null,2)));clear(v).append(c);if(d.floor){const f=card("Local policy floor");f.append(el("pre",null,JSON.stringify(d.floor,null,2)));v.append(f)}if(info.mode==="standalone"){const src=await api("/admin/policy/source"),edit=card("Edit local policy"),form=el("form"),label=el("label",null,"Policy YAML or JSON"),area=el("textarea");area.rows=18;area.value=src.raw;label.append(area);form.append(label,el("p","edge-help","Saved on the edge data volume and applied to new calls immediately. Keep a backup before broad policy changes."),el("button",null,"Save policy"));form.onsubmit=async e=>{e.preventDefault();if(!confirm("Apply this policy to new calls?"))return;try{await api("/admin/policy/source",{method:"PUT",body:{raw:area.value}});toast("Policy applied");refresh()}catch(err){toast(err.message)}};edit.append(form);v.append(edit)}const test=card("Check a tool call"),f=el("form","edge-form"),[agent,ai]=field("Agent","text","","agent"),[tool,ti]=field("Tool","text","","tool"),[args,ar]=field("Arguments (JSON)","text","{}","args"),out=el("p","muted");ti.required=true;f.append(agent,tool,args,el("button",null,"Check"));f.onsubmit=async e=>{e.preventDefault();try{const x=await api("/admin/policy/check",{method:"POST",body:{agent:ai.value,tool:ti.value,args:JSON.parse(ar.value||"{}")}});out.textContent=`Decision: ${x.decision} · rules: ${x.rules}${x.floor?" · floor: "+x.floor:""}`}catch(err){out.textContent=err.message}};test.append(f,out);v.append(test)},
 async context(v){clear(v);const [q,qi]=field("Search context","text","","q"),[labels,li]=field("Preview labels","text","","labels"),f=el("form","edge-form"),results=el("div","edge-stack");f.append(q,labels,el("button",null,"Search"));f.onsubmit=async e=>{e.preventDefault();try{const d=await api(`/admin/context/search?q=${encodeURIComponent(qi.value)}&labels=${encodeURIComponent(li.value)}`);clear(results);for(const h of d.hits||[]){const b=button(`${h.kind} · ${h.name||h.id}`,async()=>{const x=await api(`/admin/context/entity/${encodeURIComponent(h.id)}?labels=${encodeURIComponent(li.value)}`);contextDetail(h.name||h.id,x)},true);results.append(b)}if(!d.hits?.length)results.append(empty("No visible context matches."))}catch(err){toast(err.message)}};v.append(card("Organization context"),f,results)},
 async plans(v){clear(v);const grid=el("div","edge-grid");for(const [title,description] of [["Free edge","Model and tool gateway, local provider and agent keys, teams, approvals, traces and policy inspection."],["Team","Customer-hosted control plane for shared identity, policy bundles and multiple edges."],["Premium extensions","Data integration, unified context, trace mining and deterministic workflows with an offline signed license."]]){const c=card(title);c.append(el("p",null,description));grid.append(c)}v.append(grid);const c=card("Become a design partner");c.append(el("p",null,"We are inviting teams to a free, time-limited pilot of paid features with setup help and a chance to shape the product."));const a=el("a","cta","Ask about the pilot");a.href="mailto:outreach@descles.com?subject=Descles%20design%20partner%20pilot";c.append(a);v.append(c)}
};
function contactPage(v,title,description){clear(v);const hero=el("section","card premium-hero");hero.append(el("div","eyebrow","CUSTOMER-HOSTED PREMIUM"),el("h2",null,title),el("p",null,description));const actions=el("div","edge-row"),contact=el("a","cta","Contact us about premium"),pilot=el("a","secondary-link","Apply for a free design-partner pilot");contact.href="mailto:outreach@descles.com?subject="+encodeURIComponent("Descles "+title);pilot.href="mailto:outreach@descles.com?subject="+encodeURIComponent("Descles design partner pilot: "+title);actions.append(contact,pilot);hero.append(actions);v.append(hero)}
views.integrations=async v=>{
 if(!hasPanel("context")){contactPage(v,"Data integration","Connect internal sources, extract cited claims and keep organization context current on your own edge.");return}
 const d=await api("/admin/context/sync");clear(v);const intro=card("Sources stay in your network");intro.append(el("p",null,"The premium edge calls configured MCP source tools and maps their results into cited organization claims. Provider and connector credentials remain on this edge."));v.append(intro);
 const c=card("Source sync");c.append((d.tools||[]).length?table(["Source tool","Last run","Pages","Claims","Result","Action"],d.tools.map(s=>[s.tool,fmt(s.last_run),s.pages,s.claims,s.error||"Waiting for run",button("Sync now",async()=>{try{await api("/admin/context/sync/"+encodeURIComponent(s.tool),{method:"POST"});toast("Source sync completed");show("integrations")}catch(err){toast(err.message)}},true)])):empty(d.configured?"Waiting for the first source run.":"No scheduled source tools configured."));v.append(c);
 const setup=card("Source configuration");setup.append(el("p",null,"Source tools and extraction rules are loaded from the premium edge's orgctx-extractors.yaml. Sync status above updates as each source runs."));v.append(setup)
};
const contextSearchView=views.context;
function contextDetail(title,data){const entity=data.entity||{},box=el("div","edge-stack");box.append(el("p",null,`${entity.kind||"Entity"} · ${entity.id||""}`));const facts=card("Selected claims");facts.append((entity.attributes||[]).length?table(["Claim","Value","Source","Observed","Labels"],entity.attributes.map(a=>[a.predicate,JSON.stringify(a.fact?.value??a.fact?.ref??""),a.fact?.source||"—",fmt(a.fact?.observed_at),(a.fact?.labels||[]).join(", ")||"—"])):empty("No claims visible with these labels."));box.append(facts);const conflicts=(entity.attributes||[]).flatMap(a=>(a.conflicts||[]).map(f=>[a.predicate,JSON.stringify(f.value??f.ref??""),f.source||"—",fmt(f.observed_at)]));if(conflicts.length){const c=card("Conflicting source claims");c.append(table(["Claim","Other value","Source","Observed"],conflicts));box.append(c)}if(data.related?.length){const c=card("Related entities");c.append(table(["Relationship","Kind","Entity"],data.related.map(r=>[r.predicate,r.kind,r.name||r.entity])));box.append(c)}detail(title,box)}
views.context=async v=>{
 if(!hasPanel("context")){contactPage(v,"Organization context","Unify records into permission-aware entities with citations, provenance, clearance labels and visible conflicts.");return}
 await contextSearchView(v);const lead=v.querySelector(".card");if(lead)lead.append(el("p",null,"Search customer, person or project identifiers. Open a result to inspect selected facts, source claims, conflicts and related entities."));
 const c=card("Record a reviewed finding"),f=el("form","edge-form"),[entity,ei]=field("Existing entity ID or key","text","","entity"),[predicate,pi]=field("Claim name","text","","predicate"),[labels,li]=field("Clearance labels, comma separated","text","","labels"),valueLabel=el("label",null,"Value as JSON"),area=el("textarea");ei.required=pi.required=li.required=true;ei.placeholder="customer/email:ap@acme.com";pi.placeholder="account_decision";li.placeholder="sales";area.rows=5;area.value='"reviewed by operations"';valueLabel.append(area);f.append(entity,predicate,labels,valueLabel,el("button",null,"Record finding"));f.onsubmit=async e=>{e.preventDefault();try{const result=await api("/admin/context/assert",{method:"POST",body:{entity:ei.value,predicate:pi.value,labels:li.value.split(",").map(x=>x.trim()).filter(Boolean),value:JSON.parse(area.value)}});toast("Finding recorded as "+result.fact);show("context")}catch(err){toast(err.message)}};c.append(f,el("p","edge-help","This adds a cited administrator claim to an existing entity. Explicit clearance labels are required."));v.append(c)
};
views.mining=async v=>{
 if(!hasPanel("learning")){contactPage(v,"Trace mining","Turn repeated tool traces into a draft procedure, then bind inputs and review it before any execution.");return}
 const data=await api("/admin/activity?limit=500&kind=tool"),groups=new Map();for(const row of data.records||[]){if(!row.trace)continue;const g=groups.get(row.trace)||{id:row.trace,at:row.at,agent:row.agent,tools:[]};g.tools.push(row.name||"tool");groups.set(row.trace,g)}
 clear(v);v.append(note("Select at least two similar traces. Mining uses tool names and order; the edge does not record tool arguments. A mined draft cannot run until a person reviews and binds every step."));
 const c=card("Recent tool traces"),rows=[...groups.values()].map(g=>{const choice=el("input");choice.type="checkbox";choice.value=g.id;choice.className="mine-trace";choice.setAttribute("aria-label","Select trace "+g.id);return[choice,g.id,g.agent||"—",g.tools.join(" → "),fmt(g.at)]});c.append(rows.length?table(["Select","Trace","Agent","Steps","Started"],rows):empty("No tool traces yet. Route repeated tasks through this edge first."));v.append(c);
 const form=card("Create a draft"),f=el("form","edge-form"),[name,ni]=field("Workflow name","text","","name"),[support,si]=field("Minimum support (0.5–1)","number","0.6","support");ni.required=true;ni.pattern="[a-z0-9][a-z0-9-]{1,62}";ni.placeholder="customer-refund";si.min="0.5";si.max="1";si.step="0.05";f.append(name,support,el("button",null,"Mine selected traces"));f.onsubmit=async e=>{e.preventDefault();const ids=[...v.querySelectorAll(".mine-trace:checked")].map(x=>x.value);if(ids.length<2){toast("Select at least two traces");return}try{const result=await api("/admin/learning/mine",{method:"POST",body:{name:ni.value,trace_ids:ids,min_support:Number(si.value)}});toast(`Draft ${result.name} created from ${result.similar_runs} similar runs`);show("workflows")}catch(err){toast(err.message)}};form.append(f);v.append(form)
};
function workflowReview(name,plan){const box=el("div","edge-stack"),intro=el("p",null,`Review will be recorded as ${me.id}. A draft is never executable. Bind each step's arguments to declared inputs or previous results, or explicitly drop it.`);box.append(intro,el("pre",null,JSON.stringify(plan,null,2)));const form=el("form","edge-stack"),[inputs,ii]=field("Inputs, comma separated","text","","inputs"),[decision,di]=field("Decision","text","approve","decision"),label=el("label",null,"Bindings as JSON: tool name → argument templates"),area=el("textarea");area.rows=9;area.value=JSON.stringify(Object.fromEntries((plan.steps||[]).map(s=>[s.tool,s.args||{}])),null,2);label.append(area);const [drop,dr]=field("Drop steps, comma separated","text","","drop");di.required=true;form.append(inputs,decision,label,drop,el("button",null,"Record review"));form.onsubmit=async e=>{e.preventDefault();if(!["approve","reject"].includes(di.value)){toast("Decision must be approve or reject");return}try{const bind=JSON.parse(area.value);await api(`/admin/learning/workflows/${encodeURIComponent(name)}/review`,{method:"POST",body:{reviewer:me.id,decision:di.value,inputs:ii.value.split(",").map(x=>x.trim()).filter(Boolean),bind,drop:dr.value.split(",").map(x=>x.trim()).filter(Boolean)}});$("detail").close();toast("Review recorded");show("workflows")}catch(err){toast(err.message)}};box.append(form);detail("Review "+name,box)}
function workflowRun(name,plan){const box=el("div","edge-stack");box.append(el("p",null,"This will execute the reviewed steps through the edge under the agent key below. Edge policy and human approvals still apply."),el("pre",null,JSON.stringify(plan.steps,null,2)));const form=el("form","edge-stack"),[key,ki]=field("Agent key","password","","agent_key"),label=el("label",null,"Inputs as JSON"),area=el("textarea");area.rows=5;area.value=JSON.stringify(Object.fromEntries((plan.inputs||[]).map(x=>[x,""])),null,2);label.append(area);ki.required=true;form.append(key,label,el("button",null,"Run approved workflow"));form.onsubmit=async e=>{e.preventDefault();try{const inputs=JSON.parse(area.value);const job=await api(`/admin/learning/workflows/${encodeURIComponent(name)}/run`,{method:"POST",body:{agent_key:ki.value,inputs}});ki.value="";$("detail").close();watchRun(job.id)}catch(err){toast(err.message)}};box.append(form);detail("Run "+name,box)}
async function watchRun(id){try{const job=await api("/admin/learning/runs/"+encodeURIComponent(id)),box=el("div","edge-stack");box.append(el("p",null,`State: ${job.state}${job.approval_id?" · approval "+job.approval_id:""}`));if(job.state==="waiting_approval"){const a=el("a","cta","Open approvals");a.href="#approvals";a.onclick=()=>{$("detail").close();show("approvals")};box.append(a)}if(job.error)box.append(el("p","error-panel",job.error));if(job.results?.length)box.append(el("pre",null,JSON.stringify(job.results,null,2)));detail("Workflow run "+id,box);if(["running","waiting_approval"].includes(job.state))setTimeout(()=>{if(token&&$("detail").open&&$("detail-title").textContent==="Workflow run "+id)watchRun(id)},2500)}catch(err){toast(err.message)}}
views.workflows=async v=>{
 if(!hasPanel("learning")){contactPage(v,"Deterministic workflows","Review a mined plan, bind its arguments and run it without a model. Policy and approvals remain in force.");return}
 const data=await api("/admin/learning/workflows");clear(v);v.append(note("Only a reviewed plan with a matching approval digest can run. New drafts stay inert until a person binds every step."));const c=card("Workflow library"),rows=(data.workflows||[]).map(w=>[w.name,w.status,w.steps,w.mined_from?.runs||"—",button("Open",async()=>{try{const d=await api(`/admin/learning/workflows/${encodeURIComponent(w.name)}`),box=el("div","edge-stack");box.append(el("pre",null,JSON.stringify(d.plan,null,2)));if(d.review)box.append(el("p",null,`Reviewed by ${d.review.reviewer} · ${d.review.decision}`));box.append(button(d.plan.status==="draft"?"Review draft":"Run workflow",()=>{if(d.plan.status==="draft")workflowReview(w.name,d.plan);else workflowRun(w.name,d.plan)}));detail(w.name,box)}catch(err){toast(err.message)}},true)]);c.append(rows.length?table(["Workflow","State","Steps","Similar runs","Action"],rows):empty("No workflow drafts yet. Select repeated tool traces in Trace mining."));v.append(c)
};
function showKey(id,key){const pre=el("pre","edge-key",key),p=el("p",null,`Copy this key for ${id}. It will not be shown again.`);detail("Agent key",p,pre)}
function activityTable(records){return records.length?table(["Time","User","Agent","Call","Decision","Status","Trace"],records.map(r=>[fmt(r.at),r.user||"Unassigned",r.agent,r.name||r.kind,r.decision||"—",r.status,button(r.trace||"—",()=>trace(r.trace),true)])):empty("No calls recorded yet.")}
async function traceList(v,kind){const d=await api("/admin/activity?limit=500&kind="+kind);clear(v);const c=card(kind==="model"?"Recent model calls":"Recent tool calls");c.append(activityTable(d.records));v.append(c)}
async function trace(id){try{const d=await api("/admin/traces/"+encodeURIComponent(id));const content=el("div","edge-stack");for(const r of d.records||[]){const c=card(r.tool_local||r.tool||r.model||r.span_type);c.append(el("p","muted",`${fmt(r.started_at)} · ${r.status} · ${r.policy_decision||"no policy decision"}`));c.append(el("pre",null,JSON.stringify(r,null,2)));content.append(c)}if(!d.records?.length)content.append(empty("No trace records found."));detail("Trace "+id,content)}catch(e){toast(e.message)}}
$("login-form").onsubmit=async e=>{e.preventDefault();try{await connect($("token").value);$("token").value=""}catch(err){toast(err.message)}};
$("signout").onclick=disconnect;$("refresh").onclick=refresh;$("detail-close").onclick=()=>$("detail").close();
window.addEventListener("hashchange",()=>{const id=location.hash.slice(1);if(token&&id!==active)show(id)});
const saved=sessionStorage.getItem(tokenKey);if(saved)connect(saved).catch(e=>{disconnect();toast(e.message)});
