"use strict";
const $=id=>document.getElementById(id), tokenKey="descles-edge-admin";
let token="", info=null, panels=[], active="overview";
const sections={
 overview:["Overview","EDGE HEALTH","Your agents, providers and recent activity in one place.","overview"],
 providers:["Providers","UPSTREAM CREDENTIALS","Add provider keys on this edge. Keys never appear in list responses.","providers"],
 teams:["Teams","LOCAL GROUPS","Group agents for policy rules on this edge.","agents"],
 agents:["Agents & keys","ACCESS","Issue, rotate and revoke virtual keys. A new key is shown once.","agents"],
 models:["Model traces","OBSERVABILITY","Model calls and token usage recorded locally.","runs"],
 tools:["Tool traces","OBSERVABILITY","Executed or checked tools and policy decisions.","activity"],
 audit:["Audit","LOCAL RECORDS","Activity, approvals and local configuration changes.","audit"],
 approvals:["Approvals","HUMAN REVIEW","Review calls awaiting an administrator decision.","approvals"],
 policy:["Policy","ENFORCEMENT","Inspect and test the policy this edge enforces.","policies"],
 context:["Organization context","PREMIUM","Search permission-aware context on this edge.","agents"],
 plans:["Upgrade plan","TEAM & PREMIUM","More governance and context, hosted in your network.","coverage"]
};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n}
function add(parent,...children){for(const c of children)parent.append(c);return parent}
function clear(node){node.replaceChildren();return node}
function card(title){const c=el("section","card"),h=el("h2",null,title);c.append(h);return c}
function note(text){return el("div","note",text)}
function empty(text){return el("div","edge-empty",text)}
function field(label,type="text",value="",name=""){const l=el("label",null,label),i=el("input");i.type=type;i.value=value;i.name=name||label.toLowerCase().replace(/[^a-z0-9]+/g,"_");l.append(i);return [l,i]}
function button(label,fn,secondary=false){const b=el("button",secondary?"secondary":"",label);b.type="button";b.onclick=fn;return b}
function table(headers,rows){const wrap=el("div","table-wrap edge-table"),t=el("table"),head=el("tr");for(const h of headers)head.append(el("th",null,h));t.append(head);for(const values of rows){const tr=el("tr");for(const v of values){const td=el("td");if(v instanceof Node)td.append(v);else td.textContent=v==null?"":String(v);tr.append(td)}t.append(tr)}wrap.append(t);return wrap}
function fmt(t){return t?new Date(t).toLocaleString():"—"}
function toast(msg){const n=$("notice");n.textContent=msg;n.hidden=false;setTimeout(()=>{n.hidden=true},5500)}
function detail(title,...contents){$("detail-title").textContent=title;add(clear($("detail-body")),...contents);$("detail").showModal()}
async function api(path,options={}){const headers={Authorization:"Bearer "+token,...options.headers};if(options.body&&typeof options.body!=="string"){headers["Content-Type"]="application/json";options.body=JSON.stringify(options.body)}const response=await fetch(path,{...options,headers,cache:"no-store"});if(response.status===401){disconnect();throw Error("Admin token rejected. Connect again.")}if(!response.ok)throw Error((await response.text()).trim()||`Request failed (${response.status})`);return response.json()}
function disconnect(){token="";sessionStorage.removeItem(tokenKey);info=null;$("workspace").hidden=true;$("login").hidden=false;$("signout").hidden=true;$("connection").textContent="Disconnected"}
async function connect(value){token=value.trim();info=await api("/admin/info");sessionStorage.setItem(tokenKey,token);$("login").hidden=true;$("workspace").hidden=false;$("signout").hidden=false;$("connection").textContent=(info.edge_id||"Edge")+" · "+info.mode;panels=(await api("/admin/panels")).panels||[];nav();await show((location.hash||"#overview").slice(1))}
function nav(){const managed=info.mode==="managed";const ids=managed?["overview","models","tools","audit","approvals","policy","plans"]:["overview","providers","teams","agents","models","tools","audit","approvals","policy","plans"];
 if(panels.some(p=>p.id==="context"))ids.splice(ids.indexOf("plans"),0,"context");const n=clear($("navigation"));for(const id of ids){const a=el("a",id===active?"active":"",sections[id][0]);a.href="#"+id;a.dataset.icon=sections[id][3];a.onclick=e=>{e.preventDefault();show(id)};n.append(a)}}
async function show(id){if(!sections[id])id="overview";active=id;location.hash=id;nav();const s=sections[id];$("breadcrumb").textContent=s[0];$("eyebrow").textContent=s[1];$("page-title").textContent=s[0];$("page-description").textContent=s[2];$("page-icon").dataset.icon=s[3];const v=clear($("view"));v.append(el("div","loading","Loading…"));try{await views[id](v)}catch(e){clear(v).append(el("div","error-panel",e.message))}}
const refresh=()=>show(active);
const views={
 async overview(v){const [a,p,g,t]=await Promise.all([api("/admin/activity?limit=100"),info.mode==="standalone"?api("/admin/providers"):Promise.resolve({providers:[]}),info.mode==="standalone"?api("/admin/agents"):Promise.resolve({agents:[]}),api("/admin/approvals?state=pending")]);const records=a.records||[],models=records.filter(r=>r.kind==="model"),tools=records.filter(r=>r.kind==="tool"),cost=models.reduce((n,r)=>n+(r.cost_usd||0),0);const grid=el("div","edge-grid");for(const [title,value,hint] of [["Model calls",models.length,"Recent local records"],["Tool calls",tools.length,"Policy-checked steps"],["Agents",g.agents.length,"Virtual identities"],["Pending",t.approvals.length,"Need a decision"]]){const c=card(title);add(c,el("strong","edge-number",value),el("small","muted",hint));grid.append(c)}clear(v).append(grid,note(`Edge ${info.edge_id} is running in ${info.mode} mode. ${p.providers.length} providers configured. Recent model cost: $${cost.toFixed(4)}. Provider credentials, traces and policy remain on this edge.`));const c=card("Recent activity");c.append(activityTable(records.slice(0,12)));v.append(c);if(info.mode==="managed")v.append(note("Team and provider administration lives in the customer-hosted workspace at /. This edge retains local traces and approvals."))},
 async providers(v){const d=await api("/admin/providers");const c=card("Configured providers");const rows=d.providers.map(p=>[p.name,p.base_url,(p.models||[]).join(", ")||"Default",p.has_key?"Stored on edge":"Missing",p.source,p.source==="console"?button("Remove",async()=>{if(!confirm(`Remove provider ${p.name}?`))return;await api("/admin/providers/"+encodeURIComponent(p.name),{method:"DELETE"});toast("Provider removed");refresh()},true):"Save the same name below to replace"]);c.append(rows.length?table(["Provider","Endpoint","Models","Key","Source","Action"],rows):empty("No provider configured yet."));const form=card("Add or replace provider");const f=el("form","edge-form");const [name,ni]=field("Provider name","text","","name"),[base,bi]=field("Base URL","url","","base_url"),[key,ki]=field("API key","password","","api_key"),[models,mi]=field("Model patterns, comma separated","text","","models");for(const i of [ni,bi,ki])i.required=true;ni.placeholder="openai";bi.placeholder="https://api.openai.com/v1";mi.placeholder="gpt-*, o4-mini";f.append(name,base,key,models,el("button",null,"Save provider"));f.onsubmit=async e=>{e.preventDefault();try{await api("/admin/providers",{method:"POST",body:{name:ni.value,base_url:bi.value,api_key:ki.value,models:mi.value.split(",").map(s=>s.trim()).filter(Boolean)}});ki.value="";toast("Provider is ready for new model calls");refresh()}catch(err){toast(err.message)}};form.append(f,el("p","edge-help","Console-managed credentials are encrypted with the edge admin token in the edge data volume. Back up the token separately; changing it requires re-entering these provider keys."));clear(v).append(c,form)},
 async teams(v){const [d,a]=await Promise.all([api("/admin/teams"),api("/admin/agents")]);const c=card("Teams");c.append(d.teams.length?table(["Team","ID","Agents","Action"],d.teams.map(t=>[t.name,t.id,a.agents.filter(x=>x.group_id===t.id).length,button("Remove",async()=>{if(!confirm(`Remove team ${t.name}?`))return;try{await api("/admin/teams/"+encodeURIComponent(t.id),{method:"DELETE"});refresh()}catch(e){toast(e.message)}},true)])):empty("No teams yet. Create a team, then assign agents to it."));const form=card("Create team"),f=el("form","edge-form"),[name,ni]=field("Team name","text","","name"),[id,ii]=field("Team ID","text","","id");ni.required=ii.required=true;ii.placeholder="engineering";f.append(name,id,el("button",null,"Create team"));f.onsubmit=async e=>{e.preventDefault();try{await api("/admin/teams",{method:"POST",body:{id:ii.value,name:ni.value}});toast("Team created");refresh()}catch(err){toast(err.message)}};form.append(f);clear(v).append(c,form)},
 async agents(v){const [d,t]=await Promise.all([api("/admin/agents"),api("/admin/teams")]);const c=card("Agent keys");const actions=a=>{const box=el("div","edge-actions");box.append(button("Rotate",async()=>{if(!confirm(`Rotate ${a.agent_id}'s key? The old key stops working immediately.`))return;try{const x=await api("/admin/agents/"+encodeURIComponent(a.agent_id)+"/rotate",{method:"POST"});showKey(a.agent_id,x.key);refresh()}catch(e){toast(e.message)}},true),button("Revoke",async()=>{if(!confirm(`Revoke ${a.agent_id} and its key?`))return;try{await api("/admin/agents/"+encodeURIComponent(a.agent_id),{method:"DELETE"});refresh()}catch(e){toast(e.message)}},true));return box};c.append(table(["Agent","User","Team","Action"],d.agents.map(a=>[a.agent_id,a.user_id||"—",a.group_id||"—",actions(a)])));const form=card("Issue agent key"),f=el("form","edge-form"),[id,ii]=field("Agent ID","text","","id"),[user,ui]=field("User ID (optional)","text","","user_id"),group=el("label",null,"Team (optional)"),select=el("select");for(const t0 of [{id:"",name:"No team"},...t.teams]){const o=el("option",null,t0.name);o.value=t0.id;select.append(o)}group.append(select);ii.required=true;ii.placeholder="agent-1";f.append(id,user,group,el("button",null,"Issue key"));f.onsubmit=async e=>{e.preventDefault();try{const x=await api("/admin/agents",{method:"POST",body:{id:ii.value,user_id:ui.value,group_id:select.value}});showKey(ii.value,x.key);refresh()}catch(err){toast(err.message)}};form.append(f,el("p","edge-help","The plaintext key is shown once. Only its SHA-256 hash is retained; issuing a key for the same agent requires rotation."));clear(v).append(c,form)},
 async models(v){await traceList(v,"model")},async tools(v){await traceList(v,"tool")},
 async audit(v){const [activity,history,approvals]=await Promise.all([api("/admin/activity?limit=500"),info.mode==="standalone"?api("/admin/audit"):Promise.resolve({events:[],integrity:"not available in managed mode"}),api("/admin/approvals")]);clear(v);v.append(note("Local records are kept on this edge. Configuration history is a convenience log, not a tamper-evident audit ledger."));const events=card("Configuration history");events.append(history.events.length?table(["Time","Action","Target"],history.events.map(x=>[fmt(x.at),x.action,x.target])):empty("No console configuration changes yet."));v.append(events);const ap=card("Approval decisions");ap.append(approvals.approvals.length?table(["Time","Agent","Tool","State","Reviewer"],approvals.approvals.map(x=>[fmt(x.decided_at||x.created_at),x.agent_id,x.tool,x.state,x.decided_by||x.by||"—"])):empty("No approval records yet."));v.append(ap);const calls=card("Model and tool activity");calls.append(activityTable(activity.records));v.append(calls)},
 async approvals(v){const d=await api("/admin/approvals?state=pending");const top=card("Pending approvals"),[reviewer,ri]=field("Your name","text",localStorage.getItem("descles-reviewer")||"","reviewer");ri.onchange=()=>localStorage.setItem("descles-reviewer",ri.value);top.append(reviewer);clear(v).append(top);if(!d.approvals.length){v.append(empty("Nothing is waiting for a decision."));return}for(const a of d.approvals){const c=card(a.tool),p=el("p","muted",`Agent ${a.agent_id} · requested ${fmt(a.created_at)} · expires ${fmt(a.expires_at)}`),pre=el("pre",null,JSON.stringify(a.args||{},null,2)),[reason,reasonInput]=field("Reason (optional)","text","","reason"),actions=el("div","edge-row");for(const decision of ["approve","deny"]){actions.append(button(decision==="approve"?"Approve":"Deny",async()=>{if(!ri.value.trim()){toast("Enter your name first");return}try{await api(`/admin/approvals/${encodeURIComponent(a.id)}/${decision}`,{method:"POST",body:{by:ri.value.trim(),reason:reasonInput.value}});toast("Decision recorded");refresh()}catch(e){toast(e.message)}},decision==="deny"))}v.append(add(c,p,pre,reason,actions))}},
 async policy(v){const d=await api("/admin/policy"),c=card("Active policy");c.append(el("pre",null,JSON.stringify(d.rules,null,2)));clear(v).append(c);if(d.floor){const f=card("Local policy floor");f.append(el("pre",null,JSON.stringify(d.floor,null,2)));v.append(f)}if(info.mode==="standalone"){const src=await api("/admin/policy/source"),edit=card("Edit local policy"),form=el("form"),label=el("label",null,"Policy YAML or JSON"),area=el("textarea");area.rows=18;area.value=src.raw;label.append(area);form.append(label,el("p","edge-help","Saved on the edge data volume and applied to new calls immediately. Keep a backup before broad policy changes."),el("button",null,"Save policy"));form.onsubmit=async e=>{e.preventDefault();if(!confirm("Apply this policy to new calls?"))return;try{await api("/admin/policy/source",{method:"PUT",body:{raw:area.value}});toast("Policy applied");refresh()}catch(err){toast(err.message)}};edit.append(form);v.append(edit)}const test=card("Check a tool call"),f=el("form","edge-form"),[agent,ai]=field("Agent","text","","agent"),[tool,ti]=field("Tool","text","","tool"),[args,ar]=field("Arguments (JSON)","text","{}","args"),out=el("p","muted");ti.required=true;f.append(agent,tool,args,el("button",null,"Check"));f.onsubmit=async e=>{e.preventDefault();try{const x=await api("/admin/policy/check",{method:"POST",body:{agent:ai.value,tool:ti.value,args:JSON.parse(ar.value||"{}")}});out.textContent=`Decision: ${x.decision} · rules: ${x.rules}${x.floor?" · floor: "+x.floor:""}`}catch(err){out.textContent=err.message}};test.append(f,out);v.append(test)},
 async context(v){clear(v);const [q,qi]=field("Search context","text","","q"),[labels,li]=field("Preview labels","text","","labels"),f=el("form","edge-form"),results=el("div","edge-stack");f.append(q,labels,el("button",null,"Search"));f.onsubmit=async e=>{e.preventDefault();try{const d=await api(`/admin/context/search?q=${encodeURIComponent(qi.value)}&labels=${encodeURIComponent(li.value)}`);clear(results);for(const h of d.hits||[]){const b=button(`${h.kind} · ${h.name||h.id}`,async()=>{const x=await api(`/admin/context/entity/${encodeURIComponent(h.id)}?labels=${encodeURIComponent(li.value)}`);detail(h.name||h.id,el("pre",null,JSON.stringify(x,null,2)))},true);results.append(b)}if(!d.hits?.length)results.append(empty("No visible context matches."))}catch(err){toast(err.message)}};v.append(card("Organization context"),f,results)},
 async plans(v){clear(v);const grid=el("div","edge-grid");for(const [title,description] of [["Free edge","Model and tool gateway, local provider and agent keys, teams, approvals, traces and policy inspection."],["Team","Customer-hosted control plane for shared identity, policy bundles and multiple edges."],["Premium extensions","Data integration, unified context, trace mining and deterministic workflows with an offline signed license."]]){const c=card(title);c.append(el("p",null,description));grid.append(c)}v.append(grid);const c=card("Become a design partner");c.append(el("p",null,"We are inviting teams to a free, time-limited pilot of paid features with setup help and a chance to shape the product."));const a=el("a","cta","Ask about the pilot");a.href="mailto:outreach@descles.com?subject=Descles%20design%20partner%20pilot";c.append(a);v.append(c)}
};
function showKey(id,key){const pre=el("pre","edge-key",key),p=el("p",null,`Copy this key for ${id}. It will not be shown again.`);detail("Agent key",p,pre)}
function activityTable(records){return records.length?table(["Time","Agent","Call","Decision","Status","Trace"],records.map(r=>[fmt(r.at),r.agent,r.name||r.kind,r.decision||"—",r.status,button(r.trace||"—",()=>trace(r.trace),true)])):empty("No calls recorded yet.")}
async function traceList(v,kind){const d=await api("/admin/activity?limit=500&kind="+kind);clear(v);const c=card(kind==="model"?"Recent model calls":"Recent tool calls");c.append(activityTable(d.records));v.append(c)}
async function trace(id){try{const d=await api("/admin/traces/"+encodeURIComponent(id));const content=el("div","edge-stack");for(const r of d.records||[]){const c=card(r.tool_local||r.tool||r.model||r.span_type);c.append(el("p","muted",`${fmt(r.started_at)} · ${r.status} · ${r.policy_decision||"no policy decision"}`));c.append(el("pre",null,JSON.stringify(r,null,2)));content.append(c)}if(!d.records?.length)content.append(empty("No trace records found."));detail("Trace "+id,content)}catch(e){toast(e.message)}}
$("login-form").onsubmit=async e=>{e.preventDefault();try{await connect($("token").value);$("token").value=""}catch(err){toast(err.message)}};
$("signout").onclick=disconnect;$("refresh").onclick=refresh;$("detail-close").onclick=()=>$("detail").close();
window.addEventListener("hashchange",()=>{const id=location.hash.slice(1);if(token&&id!==active)show(id)});
const saved=sessionStorage.getItem(tokenKey);if(saved)connect(saved).catch(e=>{disconnect();toast(e.message)});
